version: "3"
services:
  app:
    build: .
    restart: always
    command: python -u app.py
    depends_on:
      db:
        condition: service_healthy

    networks:
      - backend
      - frontend

  db:
    image: mariadb:lts
    healthcheck:
      test: ["CMD", "mariadb", "--version", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MARIADB_USER=user1
      - MARIADB_PASSWORD=password1
      - MARIADB_DATABASE=visitors
      - MARIADB_ROOT_PASSWORD=my-secret-pw
    networks:
      - backend


  proxy:
    build: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - app
    networks:
       - frontend


networks:
  backend:
  frontend: 